---
- name: Simple Windows patching
  hosts: all
  check_mode: true

  vars:
    win_update_categories:
      - CriticalUpdates
    allow_reboot: true

  tasks:
#    - name: Scan packages
#      demo.patching.win_scan_packages:
#      check_mode: false
#
#    - name: Scan Services
#      demo.patching.win_scan_services:
#      check_mode: false

    - name: Install Windows Updates
      ansible.windows.win_updates:
        category_names: "{{ win_update_categories | default(omit) }}"
        reboot: "{{ allow_reboot }}"
        state: installed
      register: patch_windows_patchingresult

    - name: Show result
      ansible.builtin.debug:
        var: patch_windows_patchingresult 


...
